inherits:
  - default
ignore-paths:
  - jutut/secret_key.py

pycodestyle:
  options:
    max-line-length: 119

pylint:
  enable:
    - trailing-whitespace
  disable:
    - consider-using-f-string
    - import-error
    - protected-access
    - django-not-configured
    - relative-beyond-top-level
  options:
    additional-builtins:
      - exec_git
      - exec_manage
      - exec_pg
      - exec_user
      - exec_venv

pyflakes:
  disable:
    - F821
