# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:10
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('course_id', models.IntegerField(db_index=True)),
                ('group_path', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('superseded_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
            ],
        ),
    ]
