# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response_grade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Good')], default=0, verbose_name='Grade'),
        ),
    ]
