# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def set_submission_id(apps, schema_editor):
    Feedback = apps.get_model('feedback', 'Feedback')

    for obj in Feedback.objects.all().only('id', 'submission_id'):
        obj.submission_id = -obj.id
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20160911_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission_html_url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.RunPython(set_submission_id, migrations.RunPython.noop),
    ]
