# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0005_feedback_exercise_submission_id_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='_response_time',
            new_name='response_time',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
