# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 19:42
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_response_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for tag', max_length=20)),
                ('slug', models.SlugField(help_text='Slug key for tag. If left blank, one is created from name', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Describe the usage or meaning of this tag', max_length=155)),
                ('color', colorfield.fields.ColorField(default='#CD0000', help_text='Color that is used as background for this tag', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacktags', to='feedback.Course')),
                ('feedbacks', models.ManyToManyField(related_name='tags', to='feedback.Feedback')),
            ],
            options={
                'ordering': ['slug'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='feedbacktag',
            unique_together=set([('course', 'slug')]),
        ),
    ]
