# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0007_feedbacktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
