# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_course_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
