# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
