# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 16:48
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_client', '0001_initial'),
        ('feedback', '0010_auto_20170123_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for tag', max_length=20)),
                ('slug', models.SlugField(help_text='Slug key for tag. If left blank, one is created from name', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Describe the usage or meaning of this tag', max_length=155)),
                ('color', colorfield.fields.ColorField(default='#CD0000', help_text='Color that is used as background for this tag', max_length=10)),
                ('api_id', models.IntegerField()),
                ('url', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='feedback.Course')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplus_client.ApiNamespace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(related_name='students', to='feedback.StudentTag'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttag',
            unique_together=set([('namespace', 'api_id')]),
        ),
    ]
