# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_studenttags'),
    ]

    operations = [
        # Add field response_notify
        migrations.AddField(
            model_name='feedback',
            name='response_notify',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No notification'), (1, 'Normal notification'), (2, 'Important notification')], default=0, verbose_name='Response notify'),
        ),
        # Update verbose name for fields
        migrations.AlterField(
            model_name='feedback',
            name='response_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Responder'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_grade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Good')], default=0, verbose_name='Response grade'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_msg',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Response message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_time',
            field=models.DateTimeField(null=True, verbose_name='Response time'),
        ),
    ]
