# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_auto_20170118_1709'),
        ('feedback', '0013_auto_20171018_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dynamic_forms.form',),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='feedback.FeedbackForm'),
        ),
    ]
