# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_auto_20171024_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='max_grade',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
