# Generated by Django 2.2.9 on 2020-01-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_auto_20180807_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='feedback.Exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.Student', verbose_name='Student'),
        ),
    ]
