# Generated by Django 3.2.13 on 2022-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_auto_20200120_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='form_data',
            field=models.JSONField(blank=True),
        ),
    ]
