# Generated by Django 4.2.2 on 2023-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_alter_feedback_form_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['consecutive_order']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='consecutive_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='parent_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
