# Generated by Django 4.2.1 on 2023-08-10 12:46

import colorfield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_remove_feedbacktag_feedbacks_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=128, verbose_name='Question key')),
                ('response_value', models.CharField(help_text='Indicate for which response values this tag should be displayed. This can be a regex pattern.', max_length=128, verbose_name='Response value')),
                ('color', colorfield.ColorField(default='#CD0000', help_text='Color that is used as background for this tag', max_length=7, verbose_name='Color')),
                ('content', models.CharField(help_text="Content which is displayed in the tag. The response value can be included by writing '{}' where the value is desired. However, it is recommended to display the value only if it is known to be short, e.g. timespent.", max_length=16, verbose_name='Content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_tag_groups', to='feedback.course')),
            ],
            options={
                'ordering': ['question_key', 'response_value'],
                'unique_together': {('course', 'question_key', 'response_value')},
            },
        ),
    ]
