# Generated by Django 4.2.13 on 2024-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_feedback_response_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_tags_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
