# Generated by Django 4.2.13 on 2024-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0023_course_student_tags_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktag',
            options={'ordering': ['-pinned', 'slug']},
        ),
        migrations.AddField(
            model_name='feedbacktag',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin tag to the beginning of the list of tags.', verbose_name='Pin'),
        ),
    ]
