# Generated by Django 4.2.18 on 2025-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_alter_feedbacktag_options_feedbacktag_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
