# Generated by Django 4.2.27 on 2026-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0025_alter_exercise_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response_notify',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No notification'), (1, 'Normal notification'), (2, 'Important notification'), (10, 'Remove notification')], default=0, verbose_name='Response notify'),
        ),
    ]
