#DEBUG = True
#SECRET_KEY = '' # will be autogenerated in secret_key.py if not specified here
#ALLOWED_HOSTS = ["*"]

#ADMINS = ( # Will emails for errors
#    ('Your Name', 'your_email@example.com'),
#)
#SERVER_EMAIL = 'root@example.com' # Error message sender
#DEFAULT_FROM_EMAIL = 'webmaster@example.com' # Other email sender

## Jutut options
#from .settings import JUTUT
# minimum length in text field to count it as filled
#JUTUT['TEXT_FIELD_MIN_LENGTH'] = 2
# List of services to show in service status page with commands to get the status
#JUTUT['SERVICE_STATUS'] = (
#    ('Django gunicorn', ('systemctl', 'status', 'www-jutut-gunicorn')),
#    ('RabbitMQ', ('systemctl', 'status', 'rabbitmq-server')),
#    ('Celery workers', ('systemctl', 'status', 'www-jutut-celery')),
#    ('Celery beat', ('systemctl', 'status', 'www-jutut-celerybeat')),
#)

## Database
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'your_db_name',
#        # use ident auth for local servers
#        # and add passwd&hostname etc for remote
#    }
#}

## Caches
#CACHES = {
#    'default': {
#        # prefer memcached with unix socket
#        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
#        'LOCATION': 'unix:/tmp/memcached.sock',
#
#        # Database cache, if memcached is not possible
#        # remember to run `./manage.py createcachetable`
#        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#        'LOCATION': 'django_cache_default',
#
#        # For development local memory
#        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#        'LOCATION': 'unique-snowflake',
#        # or dummy
#        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
#    }
#}

## Logging
# For debugging purposes
#from .settings import LOGGING
#LOGGING['loggers'].update({
#    '': {
#        'level': 'INFO',
#        'handlers': ['debug_console'],
#        'propagate': True,
#    },
#    'aplus_client.client': {
#        'level': 'DEBUG',
#    },
#    'django_lti_login': {
#        'level': 'DEBUG',
#    },
#    'django.db.backends': {
#        'level': 'DEBUG',
#    },
#})
