# Generated by Django 3.2.13 on 2022-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_upgrade_to_django2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jututuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
