# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('id',), 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
