# Generated by Django 3.2.13 on 2022-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_form_form_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_i18n',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_spec',
            field=models.JSONField(),
        ),
    ]
